database:
    mongo:
        type: mongodb
        host: mongo
        user: ${MONGO_USER}
        password: ${MONGO_PASSWORD}
        port: "27017"
        db: reports_db

    redis:
        type: redis
        host: redis
        port: "6379"
        user: ""
        password: ${REDIS_PASSWORD}
        db: "1" 

celery:
    broker:
        type: redis
        host: redis
        port: "6379"
        user: ""
        password: ${REDIS_PASSWORD}
        db: "0"

    results_backend:
        type: redis
        host: redis
        port: "6379"
        user: ""
        password: ${REDIS_PASSWORD}
        db: "2"